<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<doxygen xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="compound.xsd" version="1.8.18">
  <compounddef id="class_human_factors_1_1_exceptions_1_1_logic_error" kind="class" language="C#" prot="public">
    <compoundname>HumanFactors::Exceptions::LogicError</compoundname>
    <basecompoundref prot="public" virt="non-virtual">ApplicationException</basecompoundref>
      <sectiondef kind="public-func">
      <memberdef kind="function" id="class_human_factors_1_1_exceptions_1_1_logic_error_1ac92e254173989c01c5cb4098c1e7403e" prot="public" static="no" const="no" explicit="no" inline="yes" virt="non-virtual">
        <type></type>
        <definition>HumanFactors.Exceptions.LogicError.LogicError</definition>
        <argsstring>(string message)</argsstring>
        <name>LogicError</name>
        <param>
          <type>string</type>
          <declname>message</declname>
        </param>
        <briefdescription>
        </briefdescription>
        <detaileddescription>
        </detaileddescription>
        <inbodydescription>
        </inbodydescription>
        <location file="src/Csharp/packages/base/src/Exceptions.cs" line="118" column="16" bodyfile="src/Csharp/packages/base/src/Exceptions.cs" bodystart="118" bodyend="118"/>
      </memberdef>
      </sectiondef>
    <briefdescription>
<para>There was some logical error with what the user was trying to perform. </para>
    </briefdescription>
    <detaileddescription>
    </detaileddescription>
    <inheritancegraph>
      <node id="1">
        <label>HumanFactors.Exceptions.LogicError</label>
        <link refid="class_human_factors_1_1_exceptions_1_1_logic_error"/>
        <childnode refid="2" relation="public-inheritance">
        </childnode>
      </node>
      <node id="2">
        <label>System::ApplicationException</label>
      </node>
    </inheritancegraph>
    <collaborationgraph>
      <node id="1">
        <label>HumanFactors.Exceptions.LogicError</label>
        <link refid="class_human_factors_1_1_exceptions_1_1_logic_error"/>
        <childnode refid="2" relation="public-inheritance">
        </childnode>
      </node>
      <node id="2">
        <label>System::ApplicationException</label>
      </node>
    </collaborationgraph>
    <location file="src/Csharp/packages/base/src/Exceptions.cs" line="116" column="11" bodyfile="src/Csharp/packages/base/src/Exceptions.cs" bodystart="117" bodyend="119"/>
    <listofallmembers>
      <member refid="class_human_factors_1_1_exceptions_1_1_logic_error_1ac92e254173989c01c5cb4098c1e7403e" prot="public" virt="non-virtual"><scope>HumanFactors::Exceptions::LogicError</scope><name>LogicError</name></member>
    </listofallmembers>
  </compounddef>
</doxygen>
